### ISSUE TITLE
Issues with R Script

### ISSUE THREAD

**Issue by UlisesGascon** [rladies/news#12]
Hi all!

I was able to setup the database and R in the server, but there is an issue with the plot generation.

```
Error in plot.new() : 
  could not open file '/plots/information_schemaNArplot.jpg'
Calls: apply ... unlist -> lapply -> FUN -> plot -> plot.default -> plot.new
Execution halted
```

I created a /plots/ folder that contains all the images previously added to the zip file, as far I can see in the logs... the script was able to add some new pictures but after a while the system stops.

Please... Can you help me with this? Thanks a lot!

**Comment by UlisesGascon** [comment]
This is related to #13 💥

**Comment by chucheria** [comment]
Seems that it is trying to open something that does not exists. To save a jpg first you need to create the plot and then save it, let me take a look at the script.

**Comment by chucheria** [comment]
Closing because generate plots is commented.
